# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "12.4.0"

package:
  name: kedro-viz
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/k/kedro-viz/kedro_viz-${{ version }}.tar.gz
  sha256: c4ccc28b14395aff68fdf55d3c4edf8a2811eed9cd2667fe96c06a8cbcdd824f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-requirements-txt
    - pip
  run:
    - python >=${{ python_min }}
    - aiofiles >=22.1.0
    - click-default-group
    - fastapi <0.200.0,>=0.100.0
    - fsspec >=2021.4
    - ipython <9.0,>=7.0.0
    - kedro-telemetry >=0.6.0
    - kedro >=1.0.0
    - networkx >=2.5
    - orjson <4.0,>=3.9
    - packaging >=23.0

tests:
  - python:
      imports:
        - kedro_viz
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://kedro.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Kedro-Viz helps visualise Kedro data and analytics pipelines
  description: |
    Kedro-Viz helps visualise Kedro data and analytics pipelines
  repository: https://github.com/kedro-org/kedro-viz
  documentation: https://docs.kedro.org/projects/kedro-viz

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
    - millsks
    - zaigner
    - elanqo
